### ISSUE TITLE
Problems uploading ram patch

### ISSUE THREAD

**Issue by carmiac** [BoschSensortec/BHy1_driver_and_MCU_solution#12]
I am attempting to bring up a BHI160 with an attached BMM150 and am having problems with the ram patch.  I have implemented sensor_i2c_write and sensor_i2c_read. I have verified they are working by getting the expected values from  bhy_get_product_id(), bhy_get_revision_id() and bhy_get_rom_version(&rom_version).

However, the bhy_initialize_from_rom() function is failing with a CRC error. I've attached a logic analyzer and see that the entire ram patch is being sent, but that the CRC does not match the CRC in the rampatch file.

Specifically, for Bosch_PCB_7183_di01_BMI160-7183_di01.2.1.10836_170103.h I am getting a CRC of 0xFFFFFFFF and for the header file produced from the .fw file inside https://ae-bst.resource.bosch.com/media/_tech/media/sensor_hub_software/firmware_bhi160/Bosch_PCB_7183_di01_BMI160_BMM150-7183_di012110836_170103fw.zip, I am getting a CRC of 0x6b39024c, which does not match the one in the file of 0xcc1b542b.  

Is there a way to verify the ram patch download CRC mechanism with a test pattern or something?

**Comment by ma-harvey** [comment]
With the logic analyzer, can you verify that the firmware upload does not start until the BHI160 is ready to receive the firmware ? After power-on reset, the INT pin will go HIGH to indicate the part is ready to be programmed,

The bhy_initialize_from_rom() function is well-known and validated. The firmware file itself contains the right CRC and should match the BHI160 calculation if there are no communication errors. Do you have issues with data integrity on the bus ? What is the i2c bus speed, pull-up values and number of slaves ?

**Comment by carmiac** [comment]
With the logic analyzer, I have found that the INT pin does not go high ever if I don't communicate with the BHI160.  After calling the bhy_driver_init() function, the INT pin produces three high pulses, each approximately 100ms wide, starting approx 145ms after the start of the bhy_driver_init() function is called while the firmware is being downloaded.

There have been no data integrity issues on the bus. There are two other devices on the bus, but they are not communicating during this time. The bus speed is 400kHz.

**Comment by ma-harvey** [comment]
I believe that you may not be probing the right pin for the interrupt. Interrupt is pin 12 of the BHI160. 

Unfortunately, I cannot upload pictures here due to our company network blocking access, but after applying the power, the 

After applying INT pin will go High after about 4ms, only then can you load the firmware. The same thing applies after soft-reset, which is one of the first commands sent by our sample code. (writing 0x01  to register 0x9B).

I have not seen your schematics, but keep in mind that the BHI160 INT pin polarity is fixed to push-pull, active-high. The interrupt pin cannot be shared with another device.

**Comment by carmiac** [comment]
I've double checked the lines and I am certain that it is the INT pin and nothing else is attached.
 
Is it possible that a watchdog reset is occurring? Is there a way to tell? The pulses in the following screenshot are just over 4ms wide, which would be consistent with the chip constantly resetting itself.

![screenshot from 2018-08-06 13-29-14](https://user-images.githubusercontent.com/901761/43739517-368cc0c6-997d-11e8-9302-4478faa415a9.png)

**Comment by jpbaptista30** [comment]
Hi @carmiac 
I have the same error. Were you able to correct the error?

**Comment by carmiac** [comment]
I have not yet. Right now I strongly suspect that something is causing the BHI160 watchdog to trigger, but I don't know what.  I'll let you know if I figure it out.

**Comment by jpbaptista30** [comment]
@carmiac thank you. I have been able to start bhi for some time, but now I can not do it, I have not changed anything in the code

**Comment by carmiac** [comment]
I found the issue for my setup.  I was sending I2C writes as a pair of transactions, one for setting the register and then another for the data.  Switching it to a single transaction fixed it.

**Comment by jpbaptista30** [comment]
hi @carmiac 
I continue with the same error. could you explain better how you solved the problem?
