### ISSUE TITLE
I2c Read with STM32F401RE 

### ISSUE THREAD

**Issue by yashagni** [BoschSensortec/BHy1_driver_and_MCU_solution#2]
Hey there, 
I was trying to Read the device address of BHI 160 using STM32F401RE and STM32 CubeMx. 
Despite if trying the read the address for a very long time i was not able to read it. 
I am attaching my code here, please let me know if i m doing anything wrong. 

In the code Device_Add=0x28(I2Caddress)   , WHO_AM_I=0x90
![stm bhi160_1](https://user-images.githubusercontent.com/36442899/36148192-186abf0a-10e1-11e8-9250-2da8aef0e275.PNG)

Thanxxx

**Comment by BoschSensortec** [comment]
Hi @yashagni,

What is the delay between the write of the address and read of the data? Typically there should be a repeated start condition between the two I2C transactions. Refer page 17 of the [datasheet](https://ae-bst.resource.bosch.com/media/_tech/media/datasheets/BST-BHI160B-DS000-01-Datasheet.pdf).

**Comment by yashagni** [comment]
Hey, 
Thanks for bring the Delay to my notice, although even after give a delay of 10 ms, I am not able to receive the device address. Will debugging the code in came to know that the code is not able to go past the first if condition itself. 

Also, the schematic in the datasheet of BHI 160 shuttle board is not visible properly. 
Can I get the schematic for the latest BHI 160 shuttle board so that i can be sure that I haven't mad any mistakes in the wiring. 
 Thannxx

**Comment by BoschSensortec** [comment]
@yashagni,

Your request for the higher resolution document has been forwarded to the respective team. Will update you here when it has been updated.

**Comment by yashagni** [comment]
Thanxx for that and we were finally able to read the device address. Did not have knowledge about the shifting of bits in the device address.

Thanxx for your quick response, might need your help soon.
