### ISSUE TITLE
BHI160 wrong CRC read

### ISSUE THREAD

**Issue by HansKim747** [BoschSensortec/BHy1_driver_and_MCU_solution#5]
Hi @BoschSensortec 

We have a problem wrong CRC data read as "0x984EAB15",  CRC supposed to be read as "0xE71B319A", even though we confirmed to write whole FW data successfully. 

do you know any history why CRC show up as "0x984EAB15" incorrectly? 

thanks a lot for your help in advance~!

**Comment by ma-harvey** [comment]
Hello,

If the CRC returned by the part is different from the CRC in the firmware file header, then your statement that 
> we confirmed to write whole FW data successfully
unfortunately cannot be true. I recommend that you take a close look at the required delays, which are often overlooked. You can try lowering the i2c speed in case you have communication errors.

I find easiest to use a logic analyzer with i2c decoding functionality to confirm that the host MCU 
 interprets the physical status of the pins correctly.

**Comment by HansKim747** [comment]
Hi @BoschSensortec

Still i couldn't find any clue, let me explain this situation briefly.

we are implementing BHI160_BMM150 to ESP32(Arduino AP). and we confirmed to write and read I2C data, but when we read 0x96 register, we found invalid data in it. Would you please review the whole our code what we are doing incorrectly? i attached it 
======================================================
> i2c   arr write func()
--
Reg Addr = 0x96
Reg Data =   0x05d0c408a71094180a007fa1672c400205060261808013037018059000010802
>>i2c arr read func()
Reg Addr = 0x96
Reg Data =   0x006c9d2e55000000000000000000000000000000002ed00b4a0a020000000000 // invalid data read...
========================================================
and Arduino cod is very simple with using the bosch sensortec ref code that is below, 
========================================================

#include "accelerometer_remapping_example.h"
#include <Wire.h>

// i2c init func
#define BHY_I2C_CLOCK_400K              (400000)  // 400kHz


void i2c_init_func()
{
  Wire.begin();
  Wire.setClock(BHY_I2C_CLOCK_400K); 
 
  delay(1000);
}

void setup() {
// setup start___
  Serial.begin (115200);
  // i2c_example_master_init();
  // Leonardo: wait for serial port to connect
  while (!Serial) 
  {
  }

// i2c init
  i2c_init_func();
  
  Serial.println();
  Serial.println("Start __COX Project__");
  Serial.println ();

// demo sensor()
  demo_sensor();

// loop start___
  Serial.println();
  Serial.println("Start Loop()");
}  // end of setup

void loop() {

  Serial.println(".");

  delay(1000);
}
==============================
Thansk in advance~!

**Comment by HansKim747** [comment]
Hi @BoschSensortec

BHI160 is most likely to be not ready to get fw, hence i would like to generate interrupt what BHI160 chip is ready to get fw manually, Would you please let me know which register is proper for generating interrupt to get fw from ESP32(Arduino)?

**Comment by HansKim747** [comment]
Hi @BoschSensortec
BHI160 is most likely to be not ready to get fw, hence i would like to generate interrupt what BHI160 chip is ready to get fw manually, Would you please let me know which register is proper for generating interrupt to get fw from ESP32(Arduino)?

**Comment by HansKim747** [comment]
Hi @BoschSensortec 

In your ref code, no search interrupt before sending fw, but seems to be checked interrupt "BHY_INT" after fw download... Could you point out where interrupt is generated before fw download in your code? if i try to port"accelerometer_remapping_example.c".

thanks in advance. 

=======================
void demo_sensor(void)
{
    int8_t ret;

    /* BHY Variable*/
    uint8_t                    *fifoptr           = NULL;
    uint8_t                    bytes_left_in_fifo = 0;
    uint16_t                   bytes_remaining    = 0;
    uint16_t                   bytes_read         = 0;
    bhy_data_generic_t         fifo_packet;
    bhy_data_type_t            packet_type;
    BHY_RETURN_FUNCTION_TYPE   result;
    int8_t                    bhy_mapping_matrix_init[3*3]   = {0};
    int8_t                    bhy_mapping_matrix_config[3*3] = {0,1,0,-1,0,0,0,0,1};
    struct cus_version_t      bhy_cus_version;


    DEBUG("demo_sensor()");

    /* init the bhy chip */
    if(bhy_driver_init(bhy1_fw))//    if(bhy_driver_init(&bhy1_fw))
    {
        DEBUG("Fail to init bhy\n");
    }

	

#if 1 // no interrupt
  delay(3000);
#else
    /* wait for the bhy trigger the interrupt pin go down and up again */
    while (ioport_get_pin_level(BHY_INT));

    while (!ioport_get_pin_level(BHY_INT));
#endif // 1

**Comment by HansKim747** [comment]
Hi @BoschSensortec

when i write fw as 32byte and read this, but write data is not equal to write data..if you have any information, please share it. 
==================
> i2c   arr write func()
--
Reg Addr = 0x96
Reg Data =   0x007f99e800001944007f8d687000264a7000264a7000264a7000264a7000264a
>>i2c arr read func()
Reg Addr = 0x96
Reg Data =   0x0053ba5e2e000000000000000000000000000000002ed00b4a0a020000000000
> i2c arr write func()
Reg Addr = 0x96
Reg Data =   0x7000264a7000264a7000264a7000264a7000264a7000264a7000264a7000264a
>>i2c arr read func()
Reg Addr = 0x96
Reg Data =   0x00400778e5000000000000000000000000000000002ed00b4a0a020000000000

**Comment by HansKim747** [comment]
Hi @BoschSensortec

It was resolved, thanks alot for your support~!~!
